#!/usr/bin/env python3
"""Write the teacher-facing IXL code lists (ixl-codes/*.md) from the site data.

Students reach tonight's skills through the site (via Clever); teachers don't,
so this renders the same assignments as plain Markdown tables that read well
on GitHub: one page per grade, one table per week, one row per school day, with
the exact IXL skill code(s) students should be working on.

Usage:
  python3 scripts/build_codes_list.py            # rewrite ixl-codes/
  python3 scripts/build_codes_list.py --check    # exit 1 if ixl-codes/ is stale

Inputs:  public/ixl-data.json (from sync_ixl_data.py) and the startDate /
         skipWeeks defaults in src/config.js, so dates match what the site shows.
Output:  ixl-codes/README.md and ixl-codes/grade-<K|1..8>.md
"""
import datetime as dt
import json
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(REPO_ROOT, 'public', 'ixl-data.json')
CONFIG_PATH = os.path.join(REPO_ROOT, 'src', 'config.js')
OUT_DIR = os.path.join(REPO_ROOT, 'ixl-codes')

# Mirrors GRADES / IREAD_GRADES in src/data/strings.js.
GRADES = [('K', 'Kindergarten'), ('1', '1st Grade'), ('2', '2nd Grade'),
          ('3', '3rd Grade'), ('4', '4th Grade'), ('5', '5th Grade'),
          ('6', '6th Grade'), ('7', '7th Grade'), ('8', '8th Grade')]
IREAD_GRADES = {'2', '3', '4'}
WEEKDAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
GENERATED_NOTE = ('<!-- Generated by scripts/build_codes_list.py from public/ixl-data.json. '
                  'Do not edit by hand: edit the Google Sheet and run `npm run sync-data`. -->')


def read_calendar_config():
    """Pull the startDate / skipWeeks defaults out of src/config.js."""
    src = open(CONFIG_PATH, encoding='utf-8').read()
    start = re.search(r"startDate:.*?'(\d{4}-\d{2}-\d{2})'", src)
    skips = re.search(r'skipWeeks:\s*\[([^\]]*)\]', src)
    if not start or not skips:
        sys.exit('Could not read startDate/skipWeeks from src/config.js — update build_codes_list.py.')
    return (dt.date.fromisoformat(start.group(1)),
            set(re.findall(r"'(\d{4}-\d{2}-\d{2})'", skips.group(1))))


def monday_for_week(week, start, skip):
    """Same rule as mondayForWeek() in src/lib/calendar.js."""
    count, cursor = 0, start
    for _ in range(520):
        if cursor.isoformat() not in skip:
            count += 1
            if count == week:
                return cursor
        cursor += dt.timedelta(days=7)
    return cursor


def md_date(d):
    return f'{d.month}/{d.day}'


def cell(skills):
    if not skills:
        return '—'
    parts = []
    for item in skills:
        title, path = item[0].replace('|', '\\|'), item[1]
        code = item[2] if len(item) > 2 and item[2] else '(no code)'
        link = f'[{title}](https://www.ixl.com/{path})' if path else title
        parts.append(f'**`{code}`** {link}')
    return '<br>'.join(parts)


def day_skills(root, week, day):
    return ((root or {}).get(str(week)) or {}).get(str(day)) or []


def weeks_for(data, g):
    ws = set(data['math'].get(g, {})) | set(data['ela'].get(g, {}))
    return sorted(int(w) for w in ws if w.isdigit())


def grade_page(data, g, name, start, skip):
    with_iread = g in IREAD_GRADES
    weeks = weeks_for(data, g)
    out = [GENERATED_NOTE, '', f'# {name} — IXL codes by week', '',
           '[← All grades](README.md)', '',
           'Students type the **code** into the IXL search bar to open the exact skill '
           '(or click the skill name). Rows follow the "Week & Day" numbering in the Google Sheet.',
           ]
    if with_iread:
        out.append('The **IREAD** column is optional extra practice.')
    out += ['', '**Jump to week:** ' + ' · '.join(f'[{w}](#week-{w})' for w in weeks), '']

    header = '| Day | Math | Reading |' + (' IREAD (optional) |' if with_iread else '')
    rule = '|---|---|---|' + ('---|' if with_iread else '')
    for w in weeks:
        mon = monday_for_week(w, start, skip)
        fri = mon + dt.timedelta(days=4)
        out += [f'## Week {w}', '', f'_{mon:%b} {mon.day} – {fri:%b} {fri.day}, {fri.year}_', '',
                header, rule]
        for d in range(1, 6):
            date = mon + dt.timedelta(days=d - 1)
            row = [f'**Day {d}**<br>{WEEKDAYS[d - 1]} {md_date(date)}',
                   cell(day_skills(data['math'].get(g), w, d)),
                   cell(day_skills(data['ela'].get(g), w, d))]
            if with_iread:
                row.append(cell(day_skills(data['iread'], w, d)))
            out.append('| ' + ' | '.join(row) + ' |')
        out.append('')
    return '\n'.join(out)


def index_page(data, start, skip):
    last = max(max(weeks_for(data, g) or [1]) for g, _ in GRADES)
    out = [GENERATED_NOTE, '', '# IXL codes by grade, week, and day', '',
           'The exact IXL skill codes students are assigned each school night — the same '
           'skills the IXL at Home site sends them to. Pick a grade:', '',
           '| Grade | Codes |', '|---|---|']
    out += [f'| {name} | [grade-{g}.md](grade-{g}.md) |' for g, name in GRADES]
    out += ['', '## Which week is it?', '',
            'Week and day numbers match the Google Sheet ("Week 4 Day 2"). Dates follow the '
            'site calendar in `src/config.js`'
            + (' (no-school weeks are skipped).' if skip else
               '; no-school weeks are not configured yet, so after a break the site and these '
               'dates both keep counting — the week/day numbers are what matter.'),
            '', '| Week | Mon – Fri |', '|---|---|']
    for w in range(1, last + 1):
        mon = monday_for_week(w, start, skip)
        fri = mon + dt.timedelta(days=4)
        out.append(f'| {w} | {mon:%b} {mon.day} – {fri:%b} {fri.day}, {fri.year} |')
    out += ['', '## Updating', '',
            'These pages are generated. Edit the "IXL Codes for Home" Google Sheet, then run '
            '`npm run sync-data` (see the main [README](../README.md#source-of-truth-the-google-sheet)); '
            'it regenerates both the site data and these lists.', '']
    return '\n'.join(out)


def render():
    data = json.load(open(DATA_PATH, encoding='utf-8'))
    start, skip = read_calendar_config()
    files = {'README.md': index_page(data, start, skip)}
    for g, name in GRADES:
        files[f'grade-{g}.md'] = grade_page(data, g, name, start, skip)
    return files


def main():
    files = render()
    if '--check' in sys.argv[1:]:
        stale = [n for n, text in files.items()
                 if not os.path.exists(os.path.join(OUT_DIR, n))
                 or open(os.path.join(OUT_DIR, n), encoding='utf-8').read() != text]
        if stale:
            sys.exit('ixl-codes/ is out of date (' + ', '.join(stale) + '). '
                     'Run `npm run codes-list` and commit the result.')
        print('ixl-codes/ is up to date.')
        return
    os.makedirs(OUT_DIR, exist_ok=True)
    for n, text in files.items():
        with open(os.path.join(OUT_DIR, n), 'w', encoding='utf-8') as f:
            f.write(text)
    print(f'Wrote {len(files)} files to {OUT_DIR}')


if __name__ == '__main__':
    main()
